# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qgiseducation.ui'
#
# Created: Wed Jun  4 18:29:22 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QGISEducation(object):
    def setupUi(self, QGISEducation):
        QGISEducation.setObjectName(_fromUtf8("QGISEducation"))
        QGISEducation.resize(421, 816)
        self.verticalLayout = QtGui.QVBoxLayout(QGISEducation)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_working_layer = QtGui.QLabel(QGISEducation)
        self.label_working_layer.setText(_fromUtf8(""))
        self.label_working_layer.setObjectName(_fromUtf8("label_working_layer"))
        self.verticalLayout.addWidget(self.label_working_layer)
        self.label = QtGui.QLabel(QGISEducation)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.groupBox_2 = QtGui.QGroupBox(QGISEducation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textEdit = QtGui.QTextEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(QGISEducation)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.comboBox_sprectral_band_display = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_sprectral_band_display.setObjectName(_fromUtf8("comboBox_sprectral_band_display"))
        self.verticalLayout_6.addWidget(self.comboBox_sprectral_band_display)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(QGISEducation)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_profil_spectral = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_profil_spectral.setObjectName(_fromUtf8("pushButton_profil_spectral"))
        self.gridLayout_2.addWidget(self.pushButton_profil_spectral, 3, 0, 1, 1)
        self.comboBox_processing = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_processing.setObjectName(_fromUtf8("comboBox_processing"))
        self.gridLayout_2.addWidget(self.comboBox_processing, 0, 0, 1, 1)
        self.pushButton_histogramme = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_histogramme.setObjectName(_fromUtf8("pushButton_histogramme"))
        self.gridLayout_2.addWidget(self.pushButton_histogramme, 2, 0, 1, 1)
        self.comboBox_histogrammes = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_histogrammes.setObjectName(_fromUtf8("comboBox_histogrammes"))
        self.gridLayout_2.addWidget(self.comboBox_histogrammes, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(QGISEducation)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_kmeans = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_kmeans.setObjectName(_fromUtf8("pushButton_kmeans"))
        self.verticalLayout_4.addWidget(self.pushButton_kmeans)
        self.spinBox_kmeans = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_kmeans.setProperty("value", 5)
        self.spinBox_kmeans.setObjectName(_fromUtf8("spinBox_kmeans"))
        self.verticalLayout_4.addWidget(self.spinBox_kmeans)
        self.pushButton_plugin_classification = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_plugin_classification.setObjectName(_fromUtf8("pushButton_plugin_classification"))
        self.verticalLayout_4.addWidget(self.pushButton_plugin_classification)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox = QtGui.QGroupBox(QGISEducation)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_working_dir = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_working_dir.setObjectName(_fromUtf8("lineEdit_working_dir"))
        self.horizontalLayout.addWidget(self.lineEdit_working_dir)
        self.pushButton_working_dir = QtGui.QPushButton(self.groupBox)
        self.pushButton_working_dir.setObjectName(_fromUtf8("pushButton_working_dir"))
        self.horizontalLayout.addWidget(self.pushButton_working_dir)
        self.verticalLayout.addWidget(self.groupBox)
        self.pushButton_kmz = QtGui.QPushButton(QGISEducation)
        self.pushButton_kmz.setObjectName(_fromUtf8("pushButton_kmz"))
        self.verticalLayout.addWidget(self.pushButton_kmz)
        self.pushButton_status = QtGui.QPushButton(QGISEducation)
        self.pushButton_status.setObjectName(_fromUtf8("pushButton_status"))
        self.verticalLayout.addWidget(self.pushButton_status)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(QGISEducation)
        QtCore.QMetaObject.connectSlotsByName(QGISEducation)

    def retranslateUi(self, QGISEducation):
        QGISEducation.setWindowTitle(QtGui.QApplication.translate("QGISEducation", "QGISEducation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("QGISEducation", "Layer courrante :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("QGISEducation", "Bandes spectrales affichées", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("QGISEducation", "Affichage des bandes spectrales", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("QGISEducation", "Traitements", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_profil_spectral.setText(QtGui.QApplication.translate("QGISEducation", "Profil spectral", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_histogramme.setText(QtGui.QApplication.translate("QGISEducation", "Histogramme", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("QGISEducation", "Classification", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_kmeans.setText(QtGui.QApplication.translate("QGISEducation", "Classification non supervisée", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plugin_classification.setText(QtGui.QApplication.translate("QGISEducation", "Plugin de Classification", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("QGISEducation", "Répertoire de sortie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_working_dir.setText(QtGui.QApplication.translate("QGISEducation", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_kmz.setText(QtGui.QApplication.translate("QGISEducation", "Export KMZ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_status.setText(QtGui.QApplication.translate("QGISEducation", "Status", None, QtGui.QApplication.UnicodeUTF8))

